name: Hallo Pipeline
on: 
  push
jobs:
  hallo:
    runs-on: 
      ubuntu-latest
    steps:
      - name: Projekt herunterladen
        uses: actions/checkout@v4
      - name: Dateien anzeigen
        run: ls
      - name: Gruss ausgeben
        run: echo "Mein erster Workflow läuft!"
